marker_publisher:
  ros__parameters:
    markers:
      map_mesh:
        frame_id: "map"
        type: "mesh"
        package_name: "jrb_localization"
        mesh_file: "meshes/table2023.dae"
        use_embedded_materials: true

        pose_z: -0.2

        color_r: 1.0
        color_g: 1.0
        color_b: 1.0