/**:
  ros__parameters:
    backlight_compensation: 1
    brightness: 0
    camera_frame_id: camera_optical_link
    camera_info_url: 'package://jrb_bringup/param/robotrouge_camera_info.yaml'
    contrast: 32
    exposure_absolute: 625
    exposure_auto: 3
    exposure_auto_priority: true
    gain: 0
    gamma: 100
    hue: 0
    image_raw:
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    image_size:
    - 640
    - 480
    output_encoding: rgb8
    pixel_format: YUYV
    power_line_frequency: 1
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    saturation: 64
    sharpness: 5
    use_sim_time: false
    video_device: /dev/video0
    white_balance_temperature: 4600
    white_balance_temperature_auto: true

