/go_to_goal:
  ros__parameters:
    angular_tolerance: 1.0
    forwardMovementOnly: false
    kA: 12.0
    kB: -3.0
    kP: 3.0
    linear_tolerance: 0.02
    max_angular_acceleration: 180.0
    max_angular_jerk: 90.0
    max_angular_speed: 90.0
    max_linear_acceleration: 1.0
    max_linear_jerk: 1.0
    max_linear_speed: 0.5
    rate: 10.0
    use_sim_time: false
